#:kivy 2.0.0
#:import XCamera kivy_garden.xcamera.XCamera
<CameraManager>:
    MDBoxLayout:
        orientation: "vertical"
        spacing: dp(5)

        MDToolbar:
            id: toolbar
            left_action_items: [["chevron-left", lambda x: root.exit_manager(1)]]
            elevation: 10
    
        XCamera:
            id: xcamera
            on_picture_taken: 
                root.picture_taken(*args)
                root.exit_manager(1)