#:kivy 2.0.0
<dialogItem>:    

    IconLeftWidget:
        icon: root.icon
 
<HelpContentDialog>: 
    spacing: dp(10)
    padding: dp(20)
    cols: 1
    adaptive_height: True

    IconLabel:
        text: tr._("Low carb products")
        icon: "leaf"

    IconLabel:
        text: tr._("High carb products")
        icon: "barley"

    IconLabel:
        text: tr._("Fat products")
        icon: "peanut"

    IconLabel:
        text: tr._("Protein products")
        icon: "fish"

    IconLabel:
        text: tr._("Nutrient-free products")
        icon: "shaker"

    
    # MDTextField:
    #     text: tr._("Add tags ") + "'ignoreProtein', 'ignoreHighCarb', 'ignoreLowCarb', 'ignoreFat'" + tr._(" to the recipe if you want to ignore these nutrients")
    #     disabled: True
    #     multiline: True
    #     width: root.width