#:kivy 2.0.0
<dialogItem>:    

    IconLeftWidget:
        icon: root.icon

<HelpContentDialog>: 
    spacing: dp(10)
    cols: 1
    adaptive_height: True

    MDList:
        OneLineIconListItem:
            text: tr._("Low carb products")

            IconLeftWidget:
                icon: "leaf"

        OneLineIconListItem:
            text: tr._("High carb products")

            IconLeftWidget:
                icon: "barley"

        OneLineIconListItem:
            text: tr._("Fat products")

            IconLeftWidget:
                icon: "peanut"

        OneLineIconListItem:
            text: tr._("Protein products")

            IconLeftWidget:
                icon: "fish"

        OneLineIconListItem:
            text: tr._("Nutrient-free products")

            IconLeftWidget:
                icon: "shaker"

    MDTextField:
        text: tr._("Add tags ") + "'ignoreProtein', 'ignoreHighCarb', 'ignoreLowCarb', 'ignoreFat'" + tr._(" to the recipe if you want to ignore these nutrients")
        disabled: True
        multiline: True
        width: root.width