# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

env:
  buildozer_workdir: menuGeneratorApp

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  android_debug:
    name: Android (debug)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: ${{ env.buildozer_workdir }}
          command: buildozer android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: debug
          path: ${{ steps.buildozer.outputs.filename }}
